# Generated by Django 6.0.2 on 2026-03-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff')], default='user', max_length=20),
        ),
    ]
